app/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, BooleanField, IntegerField, SelectField
from wtforms.validators import ValidationError, DataRequired, Length
from flask_babel import _, lazy_gettext as _l
from app.models import User
#from markupsafe import Markup


class EditProfileForm(FlaskForm):
    username = StringField(_l('Username'), validators=[DataRequired()])
    about_me = TextAreaField(_l('About me'), validators=[Length(min=0, max=140)])
    submit = SubmitField(_l('Submit'))

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()

            if user is not None:
                raise ValidationError(_('This username is already being used. Please use a different one.'))


class PostForm(FlaskForm):
    post = TextAreaField(_l('Share an Idea'), validators=[DataRequired(), Length(min=1, max=140)])
    submit = SubmitField(_l('Submit'))


class SearchForm(FlaskForm):
    q = StringField(_l('Search'), validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, g, \
    jsonify, current_app
from flask_login import current_user, login_required
from flask_babel import _, get_locale
from guess_language import guess_language
from app import db
from app.main.forms import EditProfileForm, PostForm, \
   SearchForm
from app.models import User, Post
from app.translate import translate
from app.main import bp

# python -m venv venv
# venv\Scripts\activate

# pip freeze > requirements.txt
# pip install -r requirements.txt

@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()
    g.locale = str(get_locale())


@bp.route('/', methods = ['GET', 'POST'])
def main():
    return render_template('question_base.html')

@bp.route('/index', methods=['GET','POST'])
@login_required
def index():

    form = PostForm()
    if form.validate_on_submit():
        language = guess_language(form.post.data)
        if language == 'UNKNOWN' or len(language) > 5:
            language = ''
        post = Post(body=form.post.data, author=current_user, language=language)
        db.session.add(post)
        db.session.commit()
        flash(_('Your idea is posted!'))
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)

    if posts.has_next:
        next_url = url_for('main.index', page=posts.next_num)
    else:
        next_url = None

    if posts.has_prev:
        prev_url = url_for('main.index', page=posts.prev_num)
    else:
        prev_url = None

    return render_template('index.html', title=_('Home Page'), form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)

@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)


    if posts.has_next:
        next_url = url_for('main.user', username=user.username, page=posts.next_num)
    else:
        next_url = None

    if posts.has_prev:
        prev_url = url_for('main.user', username=user.username,  page=posts.prev_num)
    else:
        prev_url = None

    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash(_('Your profile changes have been saved.'))
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', title='Edit Profile', form=form)


@bp.route('/follow/<username>')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(_('User %(username) not found', username=username))
        return redirect(url_for('main.index'))

    if user == current_user:
        flash(_('You cannot follow yourself!'))
        return redirect(url_for('main.user', username=username))

    current_user.follow(user)
    db.session.commit()
    flash(_('You are now following %(username)', username=username))
    return redirect(url_for('main.user', username=username))

@bp.route('/unfollow/<username>')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(_('User %(username) not found.', username=username))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash(_('You cannot unfollow yourself!'))
        return redirect(url_for('main.user', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash(_('You are not following %(username).', username=username))
    return redirect(url_for('main.user', username=username))

@bp.route('/explore')
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    posts=Post.query.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    if posts.has_next:
        next_url = url_for('main.explore', page=posts.next_num)
    else:
        next_url = None

    if posts.has_prev:
        prev_url = url_for('main.explore', page=posts.prev_num)
    else:
        prev_url = None
    return render_template('index.html', title=_('Explore'), posts=posts.items, next_url=next_url, prev_url=prev_url)


@bp.route('/translate', methods=['POST'])
@login_required
def translate_text():
    return jsonify({'text': translate(request.form['text'],
                                      request.form['source_language'],
                                      request.form['dest_language'])})

@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()
    g.locale = str(get_locale())

@bp.route('/search')
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('main.explore'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])

    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('search.html', title=_('Search'), posts=posts,
                           next_url=next_url, prev_url=prev_url)

@bp.route('/user/<username>/popup')
@login_required
def user_popup(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user_popup.html', user=user)

app/templates/_post.html
    <table class="table table-hover">
        <tr>
            <td width="70px">
                <a href="{{ url_for('main.user', username=post.author.username) }}">
                    <img src="{{ post.author.avatar(70) }}" />
                </a>
            </td>
            <td>
                {% set user_link %}
                    <span class="user_popup">
                        <a href="{{ url_for('main.user', username=post.author.username) }}">
                            {{ post.author.username }}
                        </a>
                    </span>
                {% endset %}
                {{ _('%(username)s said %(when)s',
                    username=user_link, when=moment(post.timestamp).calendar()) }}
                <br>
                <span id="post{{post.id}}">{{ post.body }}</span>

                {% if post.language and post.language != g.locale %}
                <br><br>
                <span id="translation{{post.id}}">
                    <a href="javascript:translate(
                                '#post{{ post.id }}',
                                '#translation{{ post.id }}',
                                '{{ post.language }}',
                                '{{ g.locale }}');">{{ _('Translate') }}</a>
                </span>
                {% endif %}
            </td>
        </tr>
    </table>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Lapin{% else %}{{_('Welcome to Lapin')}}{% endif %}
{% endblock %}

{% block navbar %}
    <head>

        <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='images/rabbit_icon.ico') }}">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    </head>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.main') }}">{{_('Pinla')}}</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">{{_('Home')}}</a></li>
                    <li><a href="{{ url_for('main.explore') }}">{{_('Explore')}}</a></li>

                </ul>

                {% if g.search_form %}
                <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">
                    <div class="form-group">
                        {{ g.search_form.q(size=20, class='form-control', placeholder=g.search_form.q.label.text) }}
                    </div>
                </form>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">{{_('Login')}}</a></li>
                    {% else %}
                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">{{_('Profile')}}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">{{_('Logout')}}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <body style="background-color: rgb(255,255,255)" class="base-body">
    <div style="background-color: rgb(238,236,225)" class="jumbotron container text-center">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}

        <!-- FOOTER -->
        <br>
        <br>
      <footer>
        <p>&copy; 2019 Fela, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>

      </footer>

    </div>
    </body>
{% endblock %}

{%block scripts%}
    {{super()}}
    {{moment.include_moment()}}
    {{moment.lang(g.locale)}}

    <script>
        function translate(sourceElem, destElem, sourceLang, destLang) {
            {#$(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');#}
            $.post('/translate', {
                text: $(sourceElem).text(),
                source_language: sourceLang,
                dest_language: destLang
            }).done(function(response) {
                $(destElem).text(response['text'])
            }).fail(function() {
                $(destElem).text("{{ _('Error: Could not contact server.') }}");
            });
        }

        $(function () {
            var timer = null;
            var xhr = null;
            $('.user_popup').hover(
                function(event) {
                    // mouse in event handler
                    var elem = $(event.currentTarget);
                    timer = setTimeout(function() {
                        timer = null;
                        xhr = $.ajax(
                            '/user/' + elem.first().text().trim() + '/popup').done(
                                function(data) {
                                    xhr = null;
                                    elem.popover({
                                        trigger: 'manual',
                                        html: true,
                                        animation: false,
                                        container: elem,
                                        content: data
                                    }).popover('show');
                                    flask_moment_render_all();
                                }
                            );
                    }, 50);
                },
                function(event) {
                    // mouse out event handler
                    var elem = $(event.currentTarget);
                    if (timer) {
                        clearTimeout(timer);
                        timer = null;
                    }
                    else if (xhr) {
                        xhr.abort();
                        xhr = null;
                    }
                    else {
                        elem.popover('destroy');

                    }
                }
            );
        });

        function devMode() {
            var checkBox = document.getElementById("dev-switch");
            if (checkBox.checked == false){
                //window.alert('Developer mode is ON');
            }
        }
    </script>
{%endblock%}

app/templates/edit_profile.html
{%extends "base.html"%}
{%import 'bootstrap/wtf.html' as wtf%}

{%block app_content%}
    <h1>{{_('Edit Profile')}}</h1>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
           {{wtf.quick_form(form)}}
        </div>
    </div>

{%endblock%}

app/templates/index.html
{%extends "base.html"%}
{%import 'bootstrap/wtf.html' as wtf%}

{%block app_content%}

    <h1>{{_('Hi, %(username)s!', username=current_user.username)}}</h1>

    {%if form%}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
           {{wtf.quick_form(form)}}
        </div>

    </div>
    {%endif%}

    {%for post in posts%}
        {%include '_post.html'%}
    {%endfor%}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{_('Newer posts')}}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{_('Older posts')}} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>

{%endblock%}

app/templates/main.html
{%extends "base.html"%}
{%import 'bootstrap/wtf.html' as wtf%}

{%block app_content%}
    <head>

        <style>

            .side-hr {
            display: block; height: 1px;
            border: 0; border-top: 5px solid rgb(238,236,225);
            margin: 1em 0; padding: 0;
            }


            .sidenav {
              width: 16%;
              position: fixed;
              z-index: 1;
              background: rgb(192, 80, 77);
              opacity:0.9;
              overflow: hidden;
              margin-left: 15px;
              border-radius:15px;

            }

            .sidenav a {
              padding: 6px 8px 6px 16px;
              text-decoration: none;
              font-size: 20px;
              color:black;
              display: block;
            }

            .sidenav h4{
                color:black;
                font-weight:bold;
            }

            .sidenav:hover{
            opacity:1;
            }

            .sidenav a:hover {
              color:rgb(240,230,140);
            }

            .left-col{
            width:20%;
            float:left;
            display:none;
            }

            .right-col{
            width:20%;
            float:right;
            display:none;
            overflow: hidden;
            }

            .main-col{
            width:100%;
            }

            @media screen and (min-width: 600px) {
              .left-col {display:inline}
              .right-col {display:inline}
              .main-col {width:60%}
            }


        </style>

    </head>

<body>
    <div class="container">

        <div class="row" style="display:flex;justify-content:left">

            <div class="left-col">
                <div  class="sidenav" style="margin-left:5px;">
              <h4 style="cursor:context-menu">What</h4>

                <hr class="side-hr">
                <h4 style="cursor:context-menu">Now</h4>

            </div>
            </div>

            <div class="main-col">


                <h2>Question here
                </h2>


            </div>

            <div class="right-col">
                <div  class="sidenav">
              <h4 style="cursor:context-menu" class="section">Top Rated Questions</h4>
                    <div id="popular_questions">


                        </div>

                <hr class="side-hr">
                <h4 style="cursor:context-menu">Now</h4>

            </div>
            </div>

        </div>
        <br><br>
        <div class="row" style="display:flex;justify-content:left">
            <div id="progress_bar" class="progress-bar progress-bar-info progress-bar-striped"
                    role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="">
                    </div>
                <br>
        </div>
    </div>
</body>

{%endblock%}

{%block scripts%}
    {{super()}}
    {{moment.include_moment()}}
    {{moment.lang(g.locale)}}
    <script>



    </script>
{%endblock%}

app/templates/search.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{ _('Search Results') }}</h1>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>
                    {{ _('Previous results') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Next results') }}
                    <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/user.html
{%extends "base.html"%}

{%block app_content%}

    <table>
        <tr valign="top">
            <td><img src="{{user.avatar(128)}}"</td>
            <td>
                <h1>User: {{user.username}}</h1>
                {%if user.about_me%}
                <p>{{user.about_me}}</p>
                {%endif%}
                {%if user.last_seen%}
                <p>{{_('Last seen on')}}: {{moment(user.last_seen).format('LLL')}}</p>
                {%endif%}
                <p>
                    {{user.followers.count()}} followers, {{user.followed.count()}} following.
                </p>

                {%if user == current_user%}
                <p><a href="{{url_for('main.edit_profile')}}">Edit your profile</a></p>
                {%elif not current_user.is_following(user)%}
                <p><a href="{{ url_for('main.follow', username=user.username) }}">Follow</a></p>
                {% else %}
                <p><a href="{{ url_for('main.unfollow', username=user.username) }}">Unfollow</a></p>
                {%endif%}

            </td>
        </tr>
    </table>
    <hr>
    {%for post in posts%}
        {%include '_post.html'%}
    {%endfor%}

    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{_('Newer posts')}}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{_('Older posts')}} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>

{%endblock%}

app/templates/user_popup.html
<table class="table">
    <tr>
        <td width="64" style="border: 0px;"><img src="{{ user.avatar(64) }}"></td>
        <td style="border: 0px;">
            <p>
                <a href="{{ url_for('main.user', username=user.username) }}">
                    {{ user.username }}
                </a>
            </p>
            <small>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                <p>{{ _('Last seen on') }}:
                   {{ moment(user.last_seen).format('lll') }}</p>
                {% endif %}
                <p>{{ _('%(count)d followers', count=user.followers.count()) }},
                   {{ _('%(count)d following', count=user.followed.count()) }}</p>
                {% if user != current_user %}
                    {% if not current_user.is_following(user) %}
                    <a href="{{ url_for('main.follow', username=user.username) }}">
                        {{ _('Follow') }}
                    </a>
                    {% else %}
                    <a href="{{ url_for('main.unfollow', username=user.username) }}">
                        {{ _('Unfollow') }}
                    </a>
                    {% endif %}
                {% endif %}
            </small>
        </td>
    </tr>
</table>